# Generated by Django 5.0.6 on 2024-06-23 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='MeetupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meetup_images/')),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='meetups.meetup')),
            ],
        ),
    ]
