# Generated by Django 5.0.6 on 2024-06-24 13:40

import meetups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='time',
            field=models.TimeField(default=meetups.models.default_meetup_time),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
    ]
