# Generated by Django 5.0.6 on 2024-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_meetupimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='google_maps_location',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
