# Generated by Django 5.0.6 on 2024-06-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_google_maps_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='google_maps_location',
            new_name='google_maps_link',
        ),
    ]
