# Generated by Django 5.0.6 on 2024-06-30 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_rename_google_maps_location_meetup_google_maps_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_meetups', to=settings.AUTH_USER_MODEL),
        ),
    ]
