# Generated by Django 5.0.6 on 2024-06-27 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_challenge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='photochallenge',
            old_name='details',
            new_name='description',
        ),
        migrations.CreateModel(
            name='PhotoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='photo_submissions/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='photo_submissions/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='photo_submissions/')),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='photo_challenge.photochallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='photochallengecomment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo_challenge.photosubmission'),
        ),
        migrations.AlterField(
            model_name='photochallengevote',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='photo_challenge.photosubmission'),
        ),
        migrations.DeleteModel(
            name='PhotoChallengeSubmission',
        ),
    ]
