# Generated by Django 5.0.6 on 2024-06-29 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_challenge', '0004_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='photochallengevote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='photochallengevote',
            name='image_number',
            field=models.IntegerField(choices=[(1, 'Image 1'), (2, 'Image 2'), (3, 'Image 3')], default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='photochallengevote',
            unique_together={('submission', 'user', 'image_number')},
        ),
    ]
