# Generated by Django 5.0.6 on 2024-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_challenge', '0005_alter_photochallengevote_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photochallengecomment',
            name='image_number',
            field=models.IntegerField(choices=[(1, 'Image 1'), (2, 'Image 2'), (3, 'Image 3')], default=1),
            preserve_default=False,
        ),
    ]
