# Generated by Django 5.0.6 on 2024-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_challenge', '0006_photochallengecomment_image_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photochallengesubmission',
            name='image1',
            field=models.ImageField(upload_to='photo_submissions'),
        ),
        migrations.AlterField(
            model_name='photochallengesubmission',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photo_submissions'),
        ),
        migrations.AlterField(
            model_name='photochallengesubmission',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='photo_submissions'),
        ),
    ]
