# Generated by Django 5.0.6 on 2024-06-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupimage',
            name='meetup',
        ),
        migrations.DeleteModel(
            name='Meetup',
        ),
        migrations.DeleteModel(
            name='MeetupImage',
        ),
    ]
