# Generated by Django 5.0.6 on 2024-06-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_photocategory_userphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interests',
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('camera', 'Kamera'), ('lens', 'Objektive'), ('filter', 'Filter'), ('accessory', 'Sonstiges Zubehör')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_genres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Steckbrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_editing', models.BooleanField(verbose_name='What do you think about image editing?')),
                ('preferred_shooting', models.CharField(choices=[('alone', 'Alone'), ('group', 'In a group')], max_length=20, verbose_name='Do you prefer shooting alone or in a group?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steckbrief', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
