# Generated by Django 5.0.6 on 2024-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_customuser_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photogenre',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='steckbrief',
            name='preferred_shooting',
            field=models.CharField(choices=[('alone', 'Alone'), ('group', 'In a group')], max_length=100, verbose_name='Do you prefer shooting alone or in a group?'),
        ),
    ]
