# Generated by Django 5.0.6 on 2024-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_interest_name_alter_photogenre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('camera', 'Kamera'), ('lens', 'Objektive'), ('filter', 'Filter'), ('accessory', 'Sonstiges Zubehör')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
