# Generated by Django 5.0.6 on 2024-06-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_equipment_category_alter_equipment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steckbrief',
            name='image_editing',
            field=models.BooleanField(default=False, verbose_name='What do you think about image editing?'),
        ),
        migrations.AlterField(
            model_name='steckbrief',
            name='preferred_shooting',
            field=models.CharField(choices=[('alone', 'Alone'), ('group', 'In a group')], default='alone', max_length=100, verbose_name='Do you prefer shooting alone or in a group?'),
        ),
    ]
